version: "3.6"

services:
  modpack-service:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./modpack.zip:/usr/share/nginx/html/modpack.zip
    networks:
      - minecraft-network
    container_name: modpack-service

  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "24454:24454/udp"
      - "24454:24454/tcp"
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC # Changed to FABRIC to support mods like lithium
      FABRIC_LAUNCHER_VERSION: 0.11.2
      FABRIC_LOADER_VERSION: 0.14.25
      VERSION: 1.19.2
      OPS: "LuisCed02031, ShadyGamer, Papoi"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "Jose Pablo Survival"
      MEMORY: 20G
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      ALLOW_CHEATS: "FALSE"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      MAX_PLAYERS: 50
      REMOVE_OLD_MODS: "FALSE"
      ICON: "https://avatars.githubusercontent.com/u/92172089?s=400&u=4019840738f526b24cf5f7b7670301ec38890900&v=4"
      MOTD: "\\u00a7d\\u00a7l\\u00a7nWELCOME TO iOS-LAB SERVER!\\u00a7r"
      VIEW_DISTANCE: "5"
      GENERIC_PACK: "http://modpack-service:80/modpack.zip"
    volumes:
      - mc:/data
    networks:
      - minecraft-network
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  mc: { }

networks:
  minecraft-network:
    driver: bridge
