version: "3.4"

services:
  minecraft-server:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC # Changed to FABRIC to support mods like lithium
      VERSION: 1.16.5
      OPS: "LuisCed02031, ShadyGamer, Papoi"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "Jose Pablo Survival"
      MEMORY: 20G
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      ALLOW_CHEATS: "FALSE"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      MAX_PLAYERS: 50
      REMOVE_OLD_MODS: "FALSE"
      ICON: "https://avatars.githubusercontent.com/u/92172089?s=400&u=4019840738f526b24cf5f7b7670301ec38890900&v=4"
      MOTD: "\\u00a7d\\u00a7l\\u00a7nWELCOME TO iOS-LAB SERVER!\\u00a7r"
      VIEW_DISTANCE: "5"
      CURSEFORGE_FILES: |
        medieval-mc-fabric-mmc1
        spark
        artifacts
        lithium
        fabric-chunk-pregenerator
        simple-voice-chat
        lazydfu
      CF_API_KEY: "your-curseforge-api-key" # Replace with your actual API key
    volumes:
      - mc:/data
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  mc: {}
